"""add reading_logs

Revision ID: 948ef4080da2
Revises: cc2e41089551
Create Date: 2026-07-06 18:58:21.058660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948ef4080da2'
down_revision = 'cc2e41089551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'log_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading_logs')
    # ### end Alembic commands ###
